[package]
name = "hmt-backend-native"
description = "Compile Cranelift IR into native machine code by auto-detecting the host architecture"
version = "0.1.13"
edition = "2021"

[dependencies]
anyhow = "1.0.101"
clap = { version = "4.5.58", features = ["derive", "env"] }
cranelift = { version = "0.128.3", features = ["module", "object", "native"] }
cranelift-reader = "0.128.3"
