[package]
name = "hmt-backend-native"
description = "Compile Cranelift IR into native machine code by auto-detecting the host architecture"
version = "0.1.10"
edition = "2021"

[dependencies]
anyhow = "1.0.100"
clap = { version = "4.5.54", features = ["derive", "env"] }
cranelift = { version = "0.127.1", features = ["module", "object", "native"] }
cranelift-reader = "0.127.1"
